name: Documentation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Check README exists
      run: |
        if [ ! -f README.md ]; then
          echo "ERROR: README.md not found!"
          exit 1
        fi
        echo "✓ README.md found"
    
    - name: Check AGENTS.md exists
      run: |
        if [ ! -f AGENTS.md ]; then
          echo "ERROR: AGENTS.md not found!"
          exit 1
        fi
        echo "✓ AGENTS.md found"
    
    - name: Check CHANGELOG.md exists
      run: |
        if [ ! -f CHANGELOG.md ]; then
          echo "ERROR: CHANGELOG.md not found!"
          exit 1
        fi
        echo "✓ CHANGELOG.md found"
    
    - name: Check CONTRIBUTING.md exists
      run: |
        if [ ! -f CONTRIBUTING.md ]; then
          echo "ERROR: CONTRIBUTING.md not found!"
          exit 1
        fi
        echo "✓ CONTRIBUTING.md found"
    
    - name: Check for broken links in README
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/markdown-link-check-config.json'
      continue-on-error: true
    
    - name: Validate Markdown Syntax
      run: |
        npm install -g markdownlint-cli
        markdownlint '**/*.md' --ignore node_modules --config .github/workflows/markdownlint-config.json || true
      continue-on-error: true
